development:
  address: "smtp.gmail.com"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "jimmyhoo7719@gmail.com"
  password: "hsnu1009"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.org"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "jimmyhoo7719@gmail.com"
  password: "hsnu1009"
  enable_starttls_auto: true